// tips
export const SHOW_LOADING_MESSAGE = 'SHOW_LOADING_MESSAGE';
export const HIDE_LOADING_MESSAGE = 'HIDE_LOADING_MESSAGE';

// topbar
export const SHOW_TOPBAR_SEARCH_MODAL = 'SHOW_TOPBAR_SEARCH_MODAL';
export const HIDE_TOPBAR_SEARCH_MODAL = 'HIDE_TOPBAR_SEARCH_MODAL';
export const TOGGLE_TOPBAR_SEARCH_MODAL = 'TOGGLE_TOPBAR_SEARCH_MODAL';